apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: gatewayclass
spec:
  controllerName: "hashicorp.com/consul-api-gateway-controller"
  parametersRef:
    group: consul.hashicorp.com
    kind: GatewayClassConfig
    name: gateway-class-config
