apiVersion: v1
kind: Pod
metadata:
  name: backend
  annotations:
    consul.hashicorp.com/connect-inject: "true"
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: debian:bullseye
      command: ["sleep", "inf"]
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: backend
spec:
  protocol: "http"
