global:
  image: teckerthashicorp/consul:dev
  imageK8S: hashicorp/consul-k8s-control-plane:1.2.1
  datacenter: dc2
  logLevel: debug
  peering:
    enabled: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
  acls:
    manageSystemACLs: true

connectInject:
  enabled: true
  default: true
  transparentProxy:
    defaultEnabled: true

dns:
  enabled: true
  enableRedirection: true

server:
  enabled: true
  replicas: 1
  extraConfig: |
    {
      "log_level": "DEBUG"
    }

meshGateway:
  enabled: true

terminatingGateways:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
