apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: external
spec:
  protocol: tcp
  destination:
    addresses:
      - "google.com"
    port: 443
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: external
spec:
  destination:
    name: external
  sources:
    - name: frontend
      action: allow
    - name: backend
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: terminating-gateway
spec:
  services:
    - name: external
