apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: dc1-frontend-to-dc2-termgw
spec:
  destination:
    name: terminating-gateway
  sources:
    - name: frontend
      action: allow
      peer: dc1
    - name: backend
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: external-google
spec:
  destination:
    name: external-google
  sources:
    - name: frontend
      action: allow
      peer: dc1
    - name: backend
      action: allow
