apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  mode: modename
  transparentProxy:
    outboundListenerPort: 8080
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: global
spec:
  splits:
    - weight: 100
      service: server
