global:
  image: hashicorppreview/consul:1.16-dev
  imageK8S: teckerthashicorp/consul-k8s-control-plane-dev
connectInject:
  apiGateway:
    manageExternalCRDs: false
apiGateway:
  enabled: true
  image: hashicorp/consul-api-gateway:0.5.4
  managedGatewayClass:
    enabled: true
