apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default
spec:
  services:
    - name: external
      consumers:
        - peer: dc1
    - name: backend
      consumers:
        - peer: dc1
