apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: external
spec:
  protocol: tcp
  destination:
    addresses:
      - "jsonplaceholder.typicode.com"
    port: 443
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: terminating-gateway
spec:
  services:
    - name: external
