apiVersion: v1
kind: Pod
metadata:
  name: lifecycle
spec:
  containers:
    - image: nginx
      name: application
      ports:
        - containerPort: 80
      volumeMounts:
        - name: static
          mountPath: /usr/share/nginx/html

  
