global:
  name: consul
  datacenter: dc1
  image: hashicorppreview/consul:1.16-dev
  imageK8S: consul-k8s-control-plane-dev:local
  imageConsulDataplane: hashicorppreview/consul-dataplane:1.2-dev
  logLevel: "debug"

server:
  replicas: 1

ui:
  enabled: true

connectInject:
  enabled: true
  default: true
  apiGateway:
    managedGatewayClass:
      nodeSelector: |
        beta.kubernetes.io/arch: amd64
      resources:
        requests:
          memory: "121Mi"
          cpu: "121m"
        limits:
          memory: "212Mi"
          cpu: "212m"

controller:
  enabled: true

