global:
  image: hashicorp/consul-enterprise:1.16.2-ent
  datacenter: dc1
  logLevel: trace
  peering:
    enabled: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
  acls:
    manageSystemACLs: true
  enterpriseLicense:
    secretName: 'consul-ent-license'
    secretKey: 'key'

connectInject:
  enabled: true
  default: true
  transparentProxy:
    defaultEnabled: true

dns:
  enabled: true
  enableRedirection: true

server:
  enabled: true
  replicas: 1
  extraConfig: |
    {
      "log_level": "TRACE"
    }

meshGateway:
  enabled: true
  replicas: 2

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
