global:
  name: consul-dc1
  datacenter: dc1
  logLevel: "trace"
  image: "hashicorp/consul:1.11.8"
  imageK8S: "hashicorp/consul-k8s-control-plane:0.45.0"
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true

dns:
  enabled: true
  enableRedirection: true

server:
  replicas: 1
  bootstrapExpect: 1
  extraConfig: |
    {
      "log_level": "TRACE"
    }

connectInject:
  enabled: true

meshGateway:
  enabled: true
  replicas: 1

controller:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
